hm: option for default linking method
nix-community/impermanence pull request #182
Opened 2024-05-08 18:31 UTC by Misterio77

Hi all!

Here's a (slightly late) follow up to https://github.com/nix-community/impermanence/pull/99.

This adds an option that allows users to change the default linking method.

Bindfs has been bothering me with the performance hits, and writing `method = symlink` for every entry is cumbersome. The default still is bindfs, so no breaking changes.

To make this implementation cleaner, I also refactored the directory type to use coercedTo (in its own commit, to be easier to review).

2024-05-08 19:00 UTC, Misterio77 commented
Can confirm there are no diffs in my home path when running this branch versus the main branch

2024-06-04 08:15 UTC, maxbfuer commented
I've been using this PR for about a week now and everything is working great on my end. Thank you both for your work on this PR and project :)

2024-06-07 09:32 UTC, talyz requested changes
Thanks a lot for your work on this! Looks great! Just some minor comments.

2024-06-07 09:32 UTC, talyz commented on home-manager.nix
> +                  This can be overrided on a per entry basis.
```suggestion
                  This can be overridden on a per entry basis.
```

2024-06-07 09:32 UTC, talyz commented on home-manager.nix
> +  getDirPath = v: v.directory;
Since you're removing all the other accessors, maybe this one should go, too?

2024-11-24 12:30 UTC, fbuchlak commented
Hi @talyz @Misterio77 Don't want to necrobump, but is there something except minor comments blocking this PR? This feature would be handy.

2025-01-25 14:50 UTC, Misterio77 commented
Hey, sorry for the delay! Got quite busy last semester. Will see if I can get this going.

2025-01-25 15:09 UTC, Misterio77 commented on home-manager.nix
> +                  This can be overrided on a per entry basis.
Thanks!

2025-01-25 15:09 UTC, Misterio77 commented on home-manager.nix
> +  getDirPath = v: v.directory;
Sounds good!

2025-01-25 15:11 UTC, Misterio77 commented on home-manager.nix
> +                  This can be overrided on a per entry basis.
Addressed: https://github.com/nix-community/impermanence/compare/68ac02aa0266326820fa540216384447f38a37fe..8825ba211a9b079f9b0c45d74645cf81b2c82b4a

2025-01-25 15:11 UTC, Misterio77 commented on home-manager.nix
> +  getDirPath = v: v.directory;
Addressed: https://github.com/nix-community/impermanence/compare/68ac02aa0266326820fa540216384447f38a37fe..8825ba211a9b079f9b0c45d74645cf81b2c82b4a

2025-01-25 15:12 UTC, Misterio77 commented
Should be good to go!

CC @talyz @fbuchlak

2025-01-25 15:24 UTC, Misterio77 commented
Oops sorry, hold on a bit. Got some eval errors after rebasing.

2025-01-25 18:51 UTC, merged

2025-01-25 18:51 UTC, talyz commented
Thanks!

2025-02-07 18:34 UTC, eyJhb commented
@Misterio77 thanks for this PR, I _REALLY_ appreciate it. I've just been patching impermanence for a long while, instead of doing it properly. Thanks for the effort! :)