home-manager: adds configurable symlink/bindfs option
nix-community/impermanence pull request #99
Opened 2022-07-14 02:31 UTC by Misterio77

Hello, all! First of all, a huge thanks to impermanence's maintainers :), I've been using it for a while and really love it.

As mentioned in https://github.com/nix-community/impermanence/issues/42, bindfs causes some issues with a few specific programs (steam, for example). I'm aware that we have options for using the NixOS module to avoid bindfs, but that may not be preferred (or possible) for some.

This PR allows for setting a `method` in `directories` lists. They can (atm) be either "bindfs" (the default if not specified) or "symlink".

I've reused the code that links files, but now it runs on `directories` that have `method = "symlink"` as well.

I made sure that changing between the two methods works reliably:
- For that end I've added a `cleanEmptyLinkTargets` activation script step that runs unmount (earlier than usual) and deletes the mount point if it's an empty directory. This handles transitioning bindfs -> symlink.
- The transition symlink -> bindfs required me to add a `mount | grep` condition on the usual unmount phase, to avoid systemd trying to unmount a symlink (causes error messagens and a few seconds of hanging during activation).

Oh, and by the way, git got a little confused with the repeated unmount code and messed up the diff. The only change I made to `mkUnmount` was adding the `mount | grep` check.

Hope this is useful, and please let me know if there's anything to be improved!

---
Fixes #42

2022-07-14 02:34 UTC, Misterio77 commented on home-manager.nix
> +  isSymlink = v: (getMethod v) == "symlink";
Some convenience

2022-07-14 02:34 UTC, Misterio77 commented on home-manager.nix
> +  mount = "${pkgs.util-linux}/bin/mount";
Moved to top level as a couple places use it now

2022-07-14 02:43 UTC, Misterio77 commented on home-manager.nix
> +  isSymlink = v: (getMethod v) == "symlink";
Some convenience.

2022-07-14 02:43 UTC, Misterio77 commented on home-manager.nix
> +              if ${mount} | grep -F ${mountPoint}' ' >/dev/null; then
This `if` is this section's actual change.

2022-07-14 02:43 UTC, Misterio77 commented on home-manager.nix
> +        mount = "${pkgs.util-linux}/bin/mount";
Moved it up as there's a few different places relying on it now.

2022-07-14 02:43 UTC, Misterio77 commented on home-manager.nix
> +                if ${mount} | grep -F ${mountPoint}' ' >/dev/null; then
Git messed up the diff, but the addition of this `if` is the actual change to `mkUnmount`.

2022-07-14 02:43 UTC, Misterio77 commented on home-manager.nix
> +
Can we somehow make the above section DRYier? Not a big fan of copying and pasting the unmount stuff (although it's already duplicated on both `mkUnmount` and `mkBindMountService`.

2022-07-14 02:43 UTC, Misterio77 commented on home-manager.nix
> +
Go home, git. You're drunk.

For the record, I didn't actually remove `mkUnmountsForPath` (it's on line 375 now), git decided to diff it that way.

2022-08-21 08:22 UTC, talyz requested changes
Diff looks good and it works as expected for me. Thanks a lot for doing this! Just one tiny thing: could you rename `path` to `directory` to match the NixOS module?

2022-08-21 21:18 UTC, Misterio77 commented
No problem at all! Thank you for this awesome tool :)

> could you `rename` path to `directory`

Done!

2022-08-21 21:24 UTC, Misterio77 commented
Oops removed the review request by mistake, sorry

2022-08-22 07:58 UTC, talyz commented
It still needs to be updated in the readme. Also, please squash the update into the previous commit.

2022-08-22 14:32 UTC, Misterio77 commented
All done :)

2022-08-27 08:56 UTC, merged

2022-08-27 08:57 UTC, talyz commented
Great work! Thank you!